### ISSUE TITLE
[Bug] pwsh 7.3 compatibility

### ISSUE THREAD

**Issue by lowlydba** [lowlydba/lowlydba.sqlserver#177]
**Describe the bug**

Using pwsh 7.3+ with dbatools in this collection will fail with import errors. More details described here: https://github.com/dataplat/dbatools/issues/8657

**Solution**

Once dbatools v2.0.0 is released, make that the new minimum required version in this collection. In the mean time, 2.0.0-preview1 can be used if pwsh 7.3+ compatibility is required. Otherwise, use <= 7.2 to ensure the collection still functions.

**Comment by briantist** [comment]
We could matrix the linux tests to perhaps run with both `>=1.x,<2` and also `>=2` ; have to do some finagling for the pre-release, and probably change our setup role to take version and pre-release switch as vars so that we can use `integration_config.yml`.

I think that we'll want to keep testing <2 for a while (or at least set a specific deprecation date some amount of time after 2 is released). In the meantime, testing against 2+ early is helpful for catching problems sooner.
