### ISSUE TITLE
Add windows authentication 

### ISSUE THREAD

**Issue by dave-vogelaar** [lowlydba/lowlydba.sqlserver#285]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

It appears that only sql authentication is allowed.  Can windows authentication be enabled as a feature?  Most places I have been are very leary of providing sql auth for higher privileged accounts.  

**Describe the solution you'd like**

Provide an ability to use a become in ansible playbook and leverage trusted authentication

**Comment by lowlydba** [comment]
Hi @dave-vogelaar, its been a few years now since I worked where this is used in production, but I believe this is already supported via DBATools underneath the collection - as long as your powershell session is authenticated, you can just omit the sql username and password and it will default to the Windows auth. 

So you just need to make sure the playbook is executing in the proper context and you're good to go.

**Comment by lowlydba** [comment]
You can check the Ansible documentation on setting up Kerberos auth for WinRM here: https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html#inventory-options

**Comment by dave-vogelaar** [comment]
Thanks for the update!
