### ISSUE TITLE
[Request] User modules supports to configure database level roles

### ISSUE THREAD

**Issue by caidingyu** [lowlydba/lowlydba.sqlserver#290]
**Is your feature request related to a problem? Please describe.**
The current user module doesn't support to configure roles.

**Describe the solution you'd like**
Be able to use the user module to configure and manage database level roles of a DB user.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by lowlydba** [comment]
Hey @caidingyu, thanks for the request! This is probably the most requested feature at this point. 

Classically, I've 'drawn the line' at keeping most of this collection focused at the server level for administration, because most tasks at the individual database layer or below tends to me more open ended (i.e. custom database roles vs fixed server roles) and I figured that since *defining* custom database roles was impractical to do outside of a custom non-query script, that managing them would be too.

I think I am finally swayed that this would be a worthwhile feature!
